### ISSUE TITLE
wrong number of arguments (given 2, expected 0..1) with link_to_add_association() after migrating to Rails 5.2

### ISSUE THREAD

**Issue by abournier** [nathanvda/cocoon#503]
Hello,

I just migrated my app from Rails 5.1.4 to Rails 5.2.0 and update the bundle.

```
# jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'cocoon'
```

Javascript:

```
//= require jquery
//= require jquery_ujs

//= require jquery-ui

//= require cocoon
//= require autocomplete-rails
```

My `link_to_add_association()` is broken in my code now:

```
link_to_add_association t(:ADD_GRAPE), f, :varietals, 'data-association-insertion-node' => "#wine-grapes ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|varietal| varietal.build_grape; varietal }, :partial => '/cloud/wines/varietal_field' 
```

The error is:
`wrong number of arguments (given 2, expected 0..1)`

If I remove the method, no issue. I don't know exactly what method it is as the number of args is not corresponding.
Same error with only `link_to_add_association t(:ADD_GRAPE), f, :varietals`

What did I miss ? Possible Jquery update issue ?

**Comment by nathanvda** [comment]
Mmmmm weird. Trying to see where we pass two variables instead of 0..1. Can you show the stack-trace of the error?

**Comment by nathanvda** [comment]
I just upgraded the cocoon-simple-form demo project to rails 5.2 and I get no errors, so that relaxes me a little bit 😛 The error you get is at the ruby end, right? While rendering the page?

**Comment by abournier** [comment]
Hi nathanvda,

I think you can be relax. ;)
Maybe it's an issue due to the use of the "protected_attributes_continued" gem ? (I use this gem for some compatibility)

The full trace:

```
activerecord (5.2.0) lib/active_record/inheritance.rb:50:in `new'
protected_attributes_continued (1.3.0) lib/active_record/mass_assignment_security/reflection.rb:8:in `build_association'
protected_attributes_continued (1.3.0) lib/active_record/mass_assignment_security/associations.rb:7:in `build_record'
protected_attributes_continued (1.3.0) lib/active_record/mass_assignment_security/associations.rb:25:in `build'
protected_attributes_continued (1.3.0) lib/active_record/mass_assignment_security/associations.rb:64:in `build'
cocoon (1.2.11) lib/cocoon/view_helpers.rb:136:in `create_object_on_association'
cocoon (1.2.11) lib/cocoon/view_helpers.rb:113:in `create_object'
cocoon (1.2.11) lib/cocoon/view_helpers.rb:95:in `link_to_add_association'
app/views/cloud/wines/_form.html.erb:131:in `_app_views_cloud_wines__form_html_erb__2063604234116481258_70128676353300'
actionview (5.2.0) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.0) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.0) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.0) lib/action_view/template.rb:157:in `render'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.0) lib/action_view/helpers/rendering_helper.rb:34:in `render'
app/views/cloud/wines/edit.html.erb:28:in `block in _app_views_cloud_wines_edit_html_erb___2467172961999634626_70128683198140'
```

Hope this helps,
Alexandre

**Comment by abournier** [comment]
Sorry, I confirm this is surely a [protected_attributes_continued gem](https://github.com/westonganger/protected_attributes_continued/issues/9) issue.

**Comment by nathanvda** [comment]
No problem. I am closing this issue then.
