### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by SimonDKnight** [nathanvda/cocoon#581]
Hi I am having an issue with using cocoon for a fairly simple form, I am getting the error wrong number of arguments (given 2, expected 1). This is very frustrating for me as I have used cocoon quite a bit in past projects but I seem to have become unstuck on this project.

Ruby 2.6.5
Rails 6.0.2

```
class Checklist < ApplicationRecord
  belongs_to :property
  has_many :checklist_questions, inverse_of: :checklist

  accepts_nested_attributes_for :checklist_questions, reject_if: :all_blank, allow_destroy: true
end

class ChecklistQuestion < ApplicationRecord
  belongs_to :checklist
end
```

new.haml
```
= simple_form_for([@property, @checklist]) do |f|
          .row
            .col-lg-6
              .form-group.mb-3
                = f.input :name, placeholder: 'Checklist Name', input_html: {class: 'form-control'}
              #checklist_questions
                .form-group.mb-3
                  = f.simple_fields_for :checklist_questions do |checklist_question|
                    = render 'checklist_question_fields', f: checklist_question
                  .links
                    = link_to_add_association 'add task', f,:checklist_questions
              .form-group.mb-3
                = f.submit "Save", class: 'btn btn-primary'
```
_checklist_question_fields.haml
```
.nested-fields
  = f.input :question
  = link_to_remove_association "remove question", f

```
Any help would be appreciated? I am not sure if I have missed something or if this is an issue with Rails 6. Thanks

**Comment by nathanvda** [comment]
The code looks ok at first sight. It might be helpful to know which part of the code triggers the error?

**Comment by SimonDKnight** [comment]
The problem is with the 
```
= link_to_add_association 'add task', f,:checklist_questions
```

If I do not add that line in then the view renders fine. If I do add it in then it fails.

**Comment by nathanvda** [comment]
Mmmmmm that is confusing. That line does not explain the error at all. Because here we see 3 parameters.

Can you please give more information? Which _actual_ line is causing the problem? Can you show me the stacktrace? Give me the literal error message? I am trying to swiftly help you while doing my day job here too, so the more information you can give me the better. 

The `link_to_add_association` renders the partial to be inserted, so maybe the error is there? (which a stacktrace of the error might reveal).

**Comment by SimonDKnight** [comment]
Thanks nathanvda I do appreciate you taking the time out of your day to help me. I think I solved the problem. I added an attribute called kind_of to my checklist question model, I then noticed in the stack trace something about kind_of? I think this is a reserved name. I removed the attribute and I no longer get the error. So the problem was nothing to do with cocoon but my own stupidity. I should have looked at the stack trace a little closer. Thanks for your help


Stack trace
activerecord (6.0.2.2) lib/active_record/attribute_methods/query.rb:36:in `attribute?'
activemodel (6.0.2.2) lib/active_model/attribute_methods.rb:383:in `kind_of?'
activerecord (6.0.2.2) lib/active_record/associations/collection_association.rb:368:in `block in delete_or_destroy'
activerecord (6.0.2.2) lib/active_record/associations/collection_association.rb:368:in `any?'
activerecord (6.0.2.2) lib/active_record/associations/collection_association.rb:368:in `delete_or_destroy'
activerecord (6.0.2.2) lib/active_record/associations/collection_association.rb:189:in `delete'
activerecord (6.0.2.2) lib/active_record/associations/collection_proxy.rb:618:in `delete'
cocoon (1.2.14) lib/cocoon/view_helpers.rb:137:in `create_object_on_association'
cocoon (1.2.14) lib/cocoon/view_helpers.rb:113:in `create_object'
cocoon (1.2.14) lib/cocoon/view_helpers.rb:95:in `link_to_add_association'
app/views/checklists/new.haml:21
haml (5.1.2) lib/haml/helpers.rb:379:in `block in capture_haml'
haml (5.1.2) lib/haml/helpers.rb:664:in `with_haml_buffer'
haml (5.1.2) lib/haml/helpers.rb:375:in `capture_haml'
haml (5.1.2) lib/haml/helpers/xss_mods.rb:63:in `capture_haml_with_haml_xss'
haml (5.1.2) lib/haml/helpers/action_view_mods.rb:46:in `capture_with_haml'
actionview (6.0.2.2) lib/action_view/helpers/form_helper.rb:452:in `form_for'
haml (5.1.2) lib/haml/helpers/action_view_xss_mods.rb:30:in `form_for_with_haml_xss'
simple_form (5.0.1) lib/simple_form/action_view_extensions/form_helper.rb:27:in `block in simple_form_for'
simple_form (5.0.1) lib/simple_form/action_view_extensions/form_helper.rb:46:in `with_simple_form_field_error_proc'
simple_form (5.0.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in `simple_form_for'
app/views/checklists/new.haml:11
actionview (6.0.2.2) lib/action_view/base.rb:274:in `_run'
actionview (6.0.2.2) lib/action_view/template.rb:186:in `block in render'
activesupport (6.0.2.2) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.2.2) lib/action_view/template.rb:388:in `instrument_render_template'
actionview (6.0.2.2) lib/action_view/template.rb:183:in `render'
actionview (6.0.2.2) lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
actionview (6.0.2.2) lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
actionview (6.0.2.2) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (6.0.2.2) lib/action_view/renderer/template_renderer.rb:57:in `render_template'
actionview (6.0.2.2) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.2.2) lib/action_view/rendering.rb:118:in `block in _render_template'
actionview (6.0.2.2) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.2.2) lib/action_view/rendering.rb:117:in `_render_template'
actionpack (6.0.2.2) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (6.0.2.2) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.2.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.2.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.2.2) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/simonknight/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
activesupport (6.0.2.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (6.0.2.2) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.2.2) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.2.2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.2.2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
